name: publish & upload to pypi
on:
  - release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name : Build dists
        uses: pypa/gh-action-pypi-publish@release/v1
        run: pip install build && python -m build .
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
