name: Test & Report Coverage
on:
  - pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: test
        run: pip install coverage && coverage run -m unittest discover tests && coverage lcov
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
            lcov-file: coverage.lcov
